version: '3.7'
services:
    postgres:
        image: 'postgres:15'
        environment:
            POSTGRES_PASSWORD: postgrespw
            POSTGRES_USER: postgres
            POSTGRES_DB: todos
        ports:
            - 5432:5432
        volumes:
            - ./data/todos:/var/lib/postgresql/data:rw
            - ./pg-initdb.d:/docker-entrypoint-initdb.d
volumes:
    todos: